# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "651e811559e8a3787f58a758dab3784327c57d7229c23890dd52c4194c2b523a"
Private = "d4ee42a340d83a75ab6507eab0ff1af758efcaa2166df408acbc7c8fc493f001"
Address = "tls://localhost:7022"
ListenAddress = ""
Description = "Conode_11"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
