# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "c9df2b0dec8ef710b2b54f7312a898aa666ed380e5fcfdb84be9a13edbefe980"
Private = "5d82971a87843d8c7d19760eaae0d4bc40d2b73b96f5e5d123bb1f2124ad820f"
Address = "tls://localhost:7012"
ListenAddress = ""
Description = "Conode_6"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
