# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "8a44c99c6f4aa65f050b125889b5b0e88da8b6e6881b3ea503fb56c8c41c815d"
Private = "d2af399a46c0e937ca737ba3da19ef762500c2e6eaec3df1d4bb45860a278b0b"
Address = "tls://localhost:7004"
ListenAddress = ""
Description = "Conode_2"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
