# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "94c08296a5a113d23c6d581e86a050dbf35a2fcd6f6eb783d8c9ebce46a0c209"
Private = "f48642998fbd0cd6f7369bf5f7e2c6ee0bd10738689a04687004517f7a148a06"
Address = "tls://localhost:7016"
ListenAddress = ""
Description = "Conode_8"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
