# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "1b8b3cdc5d0f827b5115709652911fe6ab923c548f3e235a4d98972843a02dfa"
Private = "9ff40de2f4bff1de98b66bc0819450aadc8cd3ac05b17e68f393fff5c23d5a0c"
Address = "tls://localhost:7024"
ListenAddress = ""
Description = "Conode_12"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
