# TODO clean/uniformize how parameters are passed down the chain (via cmd arg, via env etc..) for the things that are in our control
version: '3'
services:
  # Relying Party, OpenID connect client
  rp:
    build:
      context: ./RPApp
      args:
        PORT: ${RPPORT}
        OPPORT: ${OPPORT}
    extra_hosts:
     - opapp.poc:${DOCKER_HOST_IP}
    ports:
     # publish port to allow communication with host user_agent/browser, second port = where node listen for inspector debugger
     - ${RPPORT}:${RPPORT}
     - 9229:9229
  # OpenID connect Provider (Identity provider), coreos's dex with a new daga connector
  op:
    build: 
      context: ./OPApp
      args:
        PORT: ${OPPORT}
        RPPORT: ${RPPORT}
    extra_hosts:
     - rpapp.poc:${DOCKER_HOST_IP}
    ports:
     - ${OPPORT}:${OPPORT}
  # DAGA cothority, authentication service, used by op's daga connector to provide daga authentication
  daga:
    build:
      context: ./DAGACothority
    ports:
     - ${DAGA_PORTRANGE}:${DAGA_PORTRANGE}
    environment:
     - IP=${DOCKER_HOST_IP} 
     - PORTBASE=${DAGA_PORTBASE}
    command: [$DAGA_NBNODES, $DAGA_LOGLVL]
    volumes:
      - ./DAGACothority/poc-dagacothority:/opt/poc-dagacothority
  user:
    build:
      context: ./user-agent
    ports:
     - 5900:5900
    volumes:
     - ./DAGACothority/poc-dagacothority:/opt/daga
     - ./user-agent/poc-user:/opt/user
    depends_on:
     - "daga"
    extra_hosts:
     - rpapp.poc:${DOCKER_HOST_IP}
     - opapp.poc:${DOCKER_HOST_IP}
