# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "7c977c86cc76510ba96363eef2f5ad2c589b39c0609d1e6c464c976da85d32a7"
Private = "652aa868820f6e28e7edce5b364d36d91d96a84dcc89929e0d7840af29462403"
Address = "tls://localhost:7002"
ListenAddress = ""
Description = "Conode_1"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
