# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "66b1ff3b77b4bb3fdad4344aee478f3ffa963098187f65dcdabebae4d3cf65ff"
Private = "7a52d2c9ef197b8a3e09922dcbefdc00090632453ae64d4b8465c4684e1ac106"
Address = "tls://localhost:7020"
ListenAddress = ""
Description = "Conode_10"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
