# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "b3ad7b40cc37ae094c0e014f782e13afb0e3376909e9241f3137c1789a6aa53b"
Private = "5cc1cdf5484fd8750386e5898691272f0cba52d8f5d3fe280a86424f6a39ab0f"
Address = "tls://localhost:7018"
ListenAddress = ""
Description = "Conode_9"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
